routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/hoteles', 'HotelController');
Route::resource('/habitaciones', 'HabitacionController');
Route::get('/eliminarhabitacion/{name}','HabitacionController@eliminarHabitacion');

//Route::get('/nombre_url', function () {
//  return 'Ruta prueba';
//});

//Route::get('/url_parametro/{parametro}', function ($parametro) {
//  return 'Prueba parametro '.$parametro;
//});

//Route::get('/url_parametro/{parametro}/parametro_opcional/{opcional?}', function ($parametro, $opcional = null) {
//  return 'Prueba parametro '. $parametro . $opcional;
//});

resources/views/hoteles/create.blade.php
@extends("layouts.app")

@section("title", "Registrar hotel")

@section("content")
    <br />
    {!! Form::open(['route'=> 'hoteles.store', 'method' => 'POST']) !!}

    @include('hoteles.form')

    {!! Form::submit('Registrar', ['class' => 'btn btn-primary']) !!}

    {!! Form::close() !!}
@endsection

resources/views/hoteles/edit.blade.php
@extends("layouts.app")

@section("title", "Actualizar hotel")

@section("content")
    <br />
    {!! Form::model($hotel, ['route'=> ['hoteles.update', $hotel], 'method' =>  'PUT']) !!}

    @include('hoteles.form')

    {!! Form::submit('Actualizar', ['class' => 'btn btn-primary']) !!}

    {!! Form::close() !!}
@endsection

resources/views/hoteles/form.blade.php
@include('common.errors  ')

<div class="form-group">
    <div class="row">
        <div class="col-md-6">
            {!! Form::label('name', 'Nombre') !!}
            {!! Form::text('nombre', null, ['class' => 'form-control']) !!}
        </div>
        <div class="col-md-6">
            {!! Form::label('name', 'Nit') !!}
            {!! Form::text('nit', null, ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            {!! Form::label('name', 'Ciudad') !!}
            {!! Form::select('ciudad', $ciudades, null, ['placeholder' => 'Seleccione una ciudad', 'class'=> 'form-control']) !!}
        </div>
        <div class="col-md-6">
            {!! Form::label('name', 'Numero habitaciones') !!}
            {!! Form::text('numero_habitaciones', null, ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            {!! Form::label('name', 'Dirección') !!}
            {!! Form::text('direccion', null, ['class' => 'form-control']) !!}
        </div>
    </div>
</div>

resources/views/hoteles/index.blade.php
@extends("layouts.app")

@section("title", "Listar Hoteles")

@section('botones')
<div class="pull-right">

    <a href="{{route('hoteles.create')}}" class="btn btn-sm btn-success"> Registrar Hotel </a>
</div>
@endsection

@section("message_class")success @endsection
@section("content")
    <div class="row">
        @foreach($hoteles as $hotel)
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm text-center" style="margin-top: 50px; ">
                    <img class="card-img-top mx-auto d-block" style="height: 150px; width: 200px; display: block; margin: 20px"
                         src="img/decameron_hotel.jpg" data-holder-rendered="true">
                    <div class="card-body">
                        <p class="card-text"> <b>Hotel: </b>{{$hotel->nombre}}</p>
                        <p><b>Ciudad: </b>{{\Hotel\Hotel::get_ciudad($hotel->ciudad)}}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{{url("/hoteles",$hotel->id)}}" class="btn btn-sm btn-success"> Ver </a>
                                <a href="{{url("/hoteles",$hotel->id)}}/edit" class="btn btn-sm btn-primary"> Editar </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection

resources/views/hoteles/show.blade.php
@extends("layouts.app")

@section("title", "Ver Hotel")


@section('botones')
    <div class="pull-right">

        <a href="{{route('habitaciones.create')}}" class="btn btn-sm btn-success"> Registrar Habitación </a>
        {{--<a href="{{route('habitaciones.create', $hotel->id)}}" class="btn btn-sm btn-success"> Registrar Habitación </a>--}}
    </div>
@endsection

@section("message_class")info @endsection

@section("content")

    <img class="card-img-top mx-auto d-block" style="height: 300px; width: 400px; display: block; margin: 20px"
         src="/img/decameron_hotel.jpg" data-holder-rendered="true">

    <div class="text-center">
        <div class="row">
            <div class="col-md-12">
                <b>Hotel:</b> {{$hotel->nombre}}<br>
            </div>
            <div class="col-md-6">
                <b>Nit:</b> {{$hotel->nit}}<br>
                <b>Nro. Habitaciones</b> {{$hotel->numero_habitaciones}}
            </div>
            <div class="col-md-6">
                <b>Ciudad: </b> {{\Hotel\Hotel::get_ciudad($hotel->ciudad)}}<br>
                <b>Dirección:</b> {{$hotel->direccion}}

            </div>
        </div>
        {!! Form::open(['route'=> ['hoteles.destroy', $hotel->id], 'method' => 'DELETE']) !!}

        {!! Form::submit('Eliminar', ['class' => 'btn btn-danger']) !!}

        {!! Form::close() !!}
    </div>
    <br>
    <table id="datatable" class="table table-bordered table-condensed table-responsive-md">
        <td colspan="3" class="text-center" style="background-color: #242a30 !important; color: white;
        font-size: 16px;">Habitaciones asignadas</td>
        <tr>
            <th>
                Tipo de Habitación
            </th>
            <th>
                Acomodación
            </th>
            <th>
                Acciones
            </th>
        </tr>

        @foreach($habitaciones as $habitacion)
            <tr>
                <td>
                    {{\Hotel\TipoHabitacion::get_tipo_habitacion($habitacion->tipo_habitacion)}}
                </td>
                <td>
                    {{\Hotel\Acomodacion::get_acomodacion($habitacion->acomodacion)}}
                </td>
                <td>
                    <a href="{{route('habitaciones.edit', $habitacion->id)}}"  title="Editar"
                       class="btn btn-circle btn-icon btn-primary btn-sm"><i class="fa fa-edit"></i>
                    </a>
                    <a href="{{url('eliminarhabitacion', $habitacion->id)}}"  title="Eliminar"
                       class="btn btn-circle btn-icon btn-danger btn-sm"><i class="fa fa-trash"></i>
                    </a>

                </td>
            </tr>
        @endforeach
    </table>
@endsection